pact-macos:
  script:
    - nix-build
    - nix-build -A ghc.pact.doc
    - scripts/collectArtifacts.sh
  artifacts:
    paths:
    - public/

pact-linux:
  script:
    - nix-build --argstr system x86_64-linux
