pact-macos:
  script:
    - nix-build
    - cp -LR result build-out
    - chmod -R u+w build-out
  artifacts:
    paths:
    - build-out/

pact-linux:
  script:
    - nix-build --argstr system x86_64-linux
    - cp -LR result build-out
    - chmod -R u+w build-out
  artifacts:
    paths:
    - build-out/
