# stack yaml for ghc builds

resolver: lts-8.15

packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true
- location:
    git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  extra-dep: true
- location:
    git: https://github.com/LeventErkok/sbv.git
    commit: 3dc60340634c82f39f6c5dca2b3859d10925cfdf # with exposed registerKind
  extra-dep: true

extra-deps:
  - bound-2
  - ed25519-donna-0.1.1
  - hedgehog-0.6
  - hw-hspec-hedgehog-0.1.0.5

flags: {}

ghc-options:
  # Bump to the old max value for max-pmcheck-iterations (see:
  # https://ghc.haskell.org/trac/ghc/ticket/11822) to avoid a warning in
  # Pact.Analyze.Parse, where we use pattern synonyms + view patterns:
  "$locals": -fmax-pmcheck-iterations=10000000

extra-package-dbs: []
