# stack yaml for ghc builds

resolver: lts-12.9

packages:
  - '.'

extra-deps:
  - aeson-1.3.1.1
  - algebraic-graphs-0.2
  - crackNum-2.2
  - FloatingHex-0.4
  - compactable-0.1.2.2
  - ed25519-donna-0.1.1
  - hw-hspec-hedgehog-0.1.0.5
  - git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  - sbv-7.12
  - constraints-extras-0.2.0.0
